replicaCount: 3
image:
  repository: onsmanai/mern-client
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
env:
  - name: REACT_APP_SERVER_URL
    value: http://server:5000
ingress:
  enabled: true
  hosts:
    - host: mern-app.local
      paths:
        - path: /
